# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --line-length=120
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=120
          - --exclude=D100
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        args:
          - --ignore-missing-imports
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear~=21.9.2
          - flake8-docstrings~=1.6.0
          - pep8-naming~=0.12.1
          - flake8-qgis>=1.0.0
        args:
          - --max-line-length=120
          - --ignore=ANN101,D100,D202
          - --docstring-convention=google
  - repo: local
    hooks:
    - id: tests
      name: run tests
      entry: pytest tests -v
      language: python
      always_run: true
      pass_filenames: false
      stages: [push]  # Makes sure that tests are only run when pushing the code
