name: eis_toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.9.15,<3.11
  - rasterio >=1.2.10,<2.0.0
  - pandas >=1.5.3
  - geopandas >=0.12.2,<1.0.0
  - fiona >=1.8.22,<2.0.0
  - gdal >=3.0.2,<4.0.0
  - geos >=3.8.0,<4.0.0
  - scikit-learn >=1.2.1,<2.0.0
  - matplotlib-base >=3.7.0
  - statsmodels >=0.13.5,<1.0.0
  - keras >=2.10.0,<3.0.0
  - tensorflow >=2.10.0,<3.0.0
  - beartype >=0.13.1,<2.0.0
  - seaborn >=0.12.2
  - pykrige >=1.7.0
  - rtree >= 1.0.1
  - typer >=0.9.0
  - imbalanced-learn >= 0.11.0
  # Dependencies for testing
  - pytest >=7.2.1
