name: eis_toolkit

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.9,<3.11
  - rasterio >=1.3.0,<2.0.0
  - pandas >=1.4.3,<2.0
  - geopandas >=0.11.1,<1.0.0
  - scikit-learn >=1.1.2,<2.0.0
  - matplotlib-base
  - statsmodels >=0.13.2,<1.0.0
  - keras >=2.9.0
  - tensorflow >=2.9.1
  # Dependencies for testing
  - pytest
