name: eis_toolkit

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.10,<3.11
  - gdal >=3.4.3
  - rasterio >=1.3.0,<1.4.0
  - pandas >=1.4.3,<1.5
  - geopandas >=0.11.1,<0.12
  - scikit-learn >=1.1.2,<1.2.0
  - matplotlib-base
  - statsmodels >=0.13.2,<0.14.0
  - keras >=2.9.0
  - tensorflow >=2.9.1
  - mkdocs-material >=8.4.0,<8.5.0
  # Dependencies for testing
  - pytest
