site_name: EIS Toolkit
repo_name: 'eis_toolkit'
repo_url: 'https://github.com/GispoCoding/eis_toolkit'
copyright: 'Made by <a href="info@gispo.fi">Gispo Ltd.</a>'

# mkdocs.yml
theme:
  name: "material"

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT