[tool.poetry]
name = "eis_toolkit"
version = "0.1.0"
description = "EIS Toolkit is a comprehensive collection of tools suitable for mineral prospectivity mapping. This toolkit has been developed as part of the Exploration Information System project which has been funded by European Union."
authors = ["pavetsu14 <pauliina@gispo.fi>"]
maintainers = ["Gispo Ltd. <info@gispo.fi>"]
license = "MIT"
readme = "README.rst"
homepage = "https://eis-he.eu"
repository = "https://github.com/GispoCoding/eis_toolkit"
documentation = ""
keywords = [
    "Exploration",
    "Mineral prospectivity",
    "Horizon Europe",
    "Geology",
    "Packages"
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "1.4.3"
geopandas = "0.11.0"
scikit-learn = "1.1.1"
matplotlib = "3.5.2"
statsmodels = "0.13.2"
keras = "2.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
issues = "https://github.com/GispoCoding/eis_toolkit/issues"