[tool.poetry]
name = "eis_toolkit"
version = "0.1.0"
description = ""
authors = ["pavetsu14 <pauliina@gispo.fi>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
