name: Create EIS executable for Windows

on:
  pull_request:
    branches: [ build ]

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: building

    - uses: actions/upload-artifact@v2
      with:
        name: eis-toolkit-exe
        path: dist/windows