name: Create EIS executable for Windows

on:
  pull_request:
    branches: [ build ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: eis_toolkit
          auto-activate-base: false
          mamba-version: "*"
          channel-priority: true

      - name: Create requirements.txt
        run: |
          conda install pip
          pip freeze > requirements.txt

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9.13'
          spec: 'building/eis_toolkit_binary.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'EIS_Toolkit_executable'
          options: --onefile, --name "EIS Toolkit executable", --windowed, 