name: pre-commit

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files
